### ISSUE TITLE
서버 베포하기

### ISSUE THREAD

**Issue by WinterHana** [0NYE/FPS-backend#10]
**Description** 
============ 
#9 가 끝나고 나서, 서버 베포 설정을 본격적으로 할 예정입니다.

**Todo List** 
============ 
- [x] config 설정하기
- [x] Gunicorn, Nginx 적용

**문제점 해결 후 다시 서버에 반영하기**
- [x] 1. DB 연결
- [x] 2. 이미지 유사도 송신 형식 구현
- [x] 3. 반영 후 테스트

**발견된 문제점(230516)**
- [x] 이미지를 저장하는 OpenCV의 cv2.imwrite()를 사용하는데 절대 경로로만 이미지가 저장됩니다. 이게 왜 문제냐면 우분투 서버에서 돌리는 경로는 또 달라서, 서버와 로컬을 번갈아가며 테스트할 때마다 경로를 바꿔야하는 귀찮음이 생깁니다... 정 안되면 이렇게 해도 되는데 일단 이슈로 올립니다.
- [ ] 이미지와 유사도 점수를 보내는 과정에서, json 형식으로는 이미지 바이너리 데이터를 전송할 수 없다고 해서 저번에 보여드린대로 html 내에 보내드릴려고 합니다. 그런데 테스트가 잘 안되서 나중에 서버 만들면 이에 대한 테스트가 필요할 거 같습니다.
-> 이 요소는 피드백 관련 이슈에서 해결할 예정입니다.

 **ETC** 
============
"점프 투 플라스트" 레퍼런스를 참고하여 Gunicorn, Nginx를 이용할 예정입니다.
https://wikidocs.net/81077

230517 수

http://3.39.151.177/
에 이제 API 형식들을 볼 수 있지만, 아직 실기능을 하지는 못합니다. 추후 수정할 예정입니다.

**Comment by jjiny0716** [comment]
경로 문제는 https://stackoverflow.com/questions/5137497/find-the-current-directory-and-files-directory를 참고하시면 좋을 것 같습니다. 현재 실행 디렉토리를 코드로 얻을 수 있어서, 이를 사용하면 해결할 수 있을 수도?
+API 형식 보기 되게 좋습니다!

**Comment by WinterHana** [comment]
넵 감사합니다! :)
주신 레퍼런스 참고해서 오늘 수정해보도록 하겠습니다!
