### ISSUE TITLE
API에 대한 피드백

### ISSUE THREAD

**Issue by WinterHana** [0NYE/FPS-backend#14]
**Description** 
============ 
서버 API에 대해서 수정할 사항을 정리합니다.

**Todo List** 
============ 
- [x] HTML, CSS, JS 코드를 문자열로 아닌 파일 자체로 DB에 저장하는 방법 연구
- [x] API 새로 만든 명세서에 따라 다시 작성하기
- [x] 이미지 비교 다시 두 이미지를 받아서 수정하는 걸로 리팩토링

 **ETC** 
============
피드백은 여기 코멘트나 디스코드로 말씀해주시면 감사하겠습니다.
명세서 링크 : https://www.notion.so/e60e60d6b95a454b9b6136878be5b95e?v=b5cfa286171f4946882bbea347a1f88e
