### ISSUE TITLE
서버에서 코드를 이용한 사이트 랜더링 작업

### ISSUE THREAD

**Issue by WinterHana** [0NYE/FPS-backend#15]
**Description** 
============ 
서버 내에서 문제 코드를 랜더링한 다음, 이미지를 생성하는 작업입니다.

**Todo List** 
============ 
- [x] 실행을 위한 자료 조사
- [x] html2image를 사용한 이미지 랜더링 - 실패
- [ ] pyppeteer를 이용한 이미지 랜더링 - 가능성 보고 테스트 중
- [ ] 클라이언트에서 이미지를 받아와서 검사하기

**현재 문제점**
- html2image를 파이썬에 import해서 사용하면, HTML, CSS 코드를 입력해서 이미지를 생성할 수 있었습니다. 실제로 로컬에서는 별 문제 없이 실행이 되었으나, 서버에서는 진행이 안되다 502 Bad Gateway를 띄웁니다. 이게 원인을 살펴보니 html2timage를 사용하기 위해서는 윈도우에서는 크롬 브라우저, 리눅스에서는 크로미움이 있어야 하는데 이 크로미움 사양이 제가 사용하고 있는 서버보다 더 높은 사양을 요구해서 그런거 같습니다. 그래서 오늘(5월 19일) 다른 방법을 시도하고, 안되면 다른 방법을 강구해야할 거 같습니다.
(한줄 요약 : 서버가 구려서 현재 방법으로는 사용 안됨)

- HTML, CSS, JS 코드를 문자열로 직접 DB에 저장을 했었는데 혹시 파일로 저장이 가능한지 한 번 살펴볼 예정입니다.
(#14 에 적을 예정)

 **ETC** 
============
**관련 레퍼런스**
- https://sites.google.com/chromium.org/driver/?pli=1
- https://mebadong.tistory.com/110
- https://softhints.com/how-to-convert-html-to-image-in-python/
- https://gebal.tistory.com/14
- https://pypi.org/project/html2image/
