### ISSUE TITLE
API에 대한 정보 조정, 성능 개선

### ISSUE THREAD

**Issue by WinterHana** [0NYE/FPS-backend#29]
**Description** 
============ 
대략적인 틀은 만들어졌으므로, 상세 정보에 대한 보충을 진행합니다.

**Todo List** 
============ 
- [x] SUBMIT Table의 "Fail_reason" 채우기
- [x] 로그인 세션 사용해서  DB 채우기 최신화하기
- [x] 이미지 유사도 성능 개선하기 -> 수치 조절 등
- [x] 이미지 점수 조정하기
흰 바탕에 글씨만 달라져도 유사도가 굉장히 높아지는 상황 발생
- [ ] 세션 CORS 해결하기

 **ETC** 
============
