### ISSUE TITLE
[FEAT] JWT 토큰 방식의 인증 방법 연구

### ISSUE THREAD

**Issue by WinterHana** [0NYE/FPS-backend#4]
**Description** 
============ 
https://wikidocs.net/book/7601
현재 이 레퍼런스를 바탕으로 자체 로그인에 대해 연구하고 있으나, 
결국 클라이언트와 연동을 하기 위해서는 서로 간의 공유 방식이 필요함을 알게 되었습니다.
그래서, JWT 토큰으로 클라이언트와 공유하는 방법을 연구하기 위해 이슈를 올립니다.

**Todo List** 
============ 
- [x] JWT 토큰 방식에 대한 이해
- [ ] 자체 로그인 방법과 함께 구현
- [ ] 클라이언트 하시는 분이랑 정보 공유 드리기

 **ETC** 
============
#### 참고한 레퍼런스
1. https://veneas.tistory.com/entry/Spring-Boot-JWT-JSON-Web-Token-%ED%86%A0%ED%81%B0-%EA%B8%B0%EB%B0%98-%EC%9D%B8%EC%A6%9D
