### ISSUE TITLE
[FEAT] Flask를 사용한 이미지 유사도 비교 서버 제작

### ISSUE THREAD

**Issue by WinterHana** [0NYE/FPS-backend#5]
**Description** 
============ 
Flask를 이용해서 이미지 유사도 비교 서버를 만듭니다.

**Todo List** 
============ 
현재 이슈는 다음과 같습니다.(추가 예정)
1. 클라이언트에서 어떻게 이미지를 가져오고, 어떻게 결과를 전달할 것인가

이슈와 관련해서 해야할 일은 다음과 같습니다.
- [x] main branch에 지금까지 만든 코드 반영 : issue#3 branch를 pull request 요청할 예정입니다.
- [x] 서버 베포하기 : 따로 서버 실행 없이 접속이 가능하게 하는게 목표입니다.
- [x] 이미지 불러오기 : 어떻게 클라이언트에서 이미지를 받아오는지 연구합니다.
- [x] 알고리즘 변경 : 이미지를 클라이언트에 받아서 비교한 결과를 다시 클라이언트에 전달합니다. 

 **ETC** 
============
이미지 유사도 관련 issue는 일단 close 했습니다.
