### ISSUE TITLE
서버와 DB 연동하기

### ISSUE THREAD

**Issue by WinterHana** [0NYE/FPS-backend#9]
**Description** 
============ 
서버와 MySQL를 연동하고 쿼리문 테스트를 합니다.

**Todo List** 
============ 
- [x] pymysql을 이용해서 편리하게 사용할 수 있게 클래스 짜기
- [x] 쿼리문 테스트해보기
- [x] MySQL vs SQLite 사용 비교하기
- [x] 서버와 연동 후 다시 테스트해보기
- [x] 상세 설계서를 참고하여 Question 테이블 구성 점검하기

 **ETC** 
============
pymysql 라이브러리를 이용해서 간단하게 설정하면 접근 가능한 것으로 확인했습니다.

**논의 내용**
============
MySQL vs SQLite 사용 논의 중입니다.
